import { sanitizeName, toSnakeCase } from '../utils/codeFormatter';

/**
 * Utility to format a JS object as indented Bicep properties.
 */
function formatBicepProperties(
  obj: Record<string, unknown>,
  indent: number
): string {
  const pad = ' '.repeat(indent);
  const lines: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;

    if (Array.isArray(value)) {
      lines.push(`${pad}${key}: [`);
      for (const item of value) {
        if (typeof item === 'object' && item !== null) {
          lines.push(`${pad}  {`);
          lines.push(
            formatBicepProperties(item as Record<string, unknown>, indent + 4)
          );
          lines.push(`${pad}  }`);
        } else {
          lines.push(`${pad}  ${formatBicepValue(item)}`);
        }
      }
      lines.push(`${pad}]`);
    } else if (typeof value === 'object') {
      lines.push(`${pad}${key}: {`);
      lines.push(
        formatBicepProperties(value as Record<string, unknown>, indent + 2)
      );
      lines.push(`${pad}}`);
    } else {
      lines.push(`${pad}${key}: ${formatBicepValue(value)}`);
    }
  }

  return lines.join('\n');
}

function formatBicepValue(value: unknown): string {
  if (typeof value === 'string') {
    if (value.startsWith('[') && value.endsWith(']')) {
      // Bicep expression
      return value.slice(1, -1);
    }
    return `'${value}'`;
  }
  if (typeof value === 'boolean') return value.toString();
  if (typeof value === 'number') return value.toString();
  return `'${String(value)}'`;
}

// API version lookup by bicep resource type prefix
const apiVersions: Record<string, string> = {
  'Microsoft.Compute/virtualMachines': '2024-03-01',
  'Microsoft.Compute/virtualMachineScaleSets': '2024-03-01',
  'Microsoft.Compute/disks': '2024-03-02',
  'Microsoft.Web/sites': '2024-04-01',
  'Microsoft.Web/serverfarms': '2024-04-01',
  'Microsoft.App/containerApps': '2024-03-01',
  'Microsoft.App/managedEnvironments': '2024-03-01',
  'Microsoft.ContainerService/managedClusters': '2024-03-01',
  'Microsoft.Network/virtualNetworks': '2024-01-01',
  'Microsoft.Network/networkSecurityGroups': '2024-01-01',
  'Microsoft.Network/loadBalancers': '2024-01-01',
  'Microsoft.Network/publicIPAddresses': '2024-01-01',
  'Microsoft.Network/applicationGateways': '2024-01-01',
  'Microsoft.Network/dnsZones': '2023-07-01-preview',
  'Microsoft.Network/networkInterfaces': '2024-01-01',
  'Microsoft.Network/privateEndpoints': '2024-01-01',
  'Microsoft.Storage/storageAccounts': '2023-05-01',
  'Microsoft.Sql/servers': '2023-08-01-preview',
  'Microsoft.Sql/servers/databases': '2023-08-01-preview',
  'Microsoft.DocumentDB/databaseAccounts': '2024-05-15',
  'Microsoft.Cache/redis': '2024-03-01',
  'Microsoft.DBforPostgreSQL/flexibleServers': '2024-03-01',
  'Microsoft.KeyVault/vaults': '2023-07-01',
  'Microsoft.Insights/components': '2020-02-02',
  'Microsoft.OperationalInsights/workspaces': '2023-09-01',
  'Microsoft.ContainerRegistry/registries': '2023-11-01-preview',
  'Microsoft.ServiceBus/namespaces': '2024-01-01',
  'Microsoft.EventHub/namespaces': '2024-01-01',
  'Microsoft.CognitiveServices/accounts': '2024-04-01-preview',
  'Microsoft.Search/searchServices': '2024-03-01-preview',
  'Microsoft.Resources/resourceGroups': '2024-03-01',
};

function getApiVersion(bicepType: string): string {
  return apiVersions[bicepType] ?? '2024-01-01';
}

import type { CanvasResource, ResourceGroup } from '../types';
import type { CSSProperties } from 'react';
import { allResources } from '../data/azureResources';

export function generateBicep(
  resources: CanvasResource[],
  resourceGroups: ResourceGroup[],
  edges: Array<{ source: string; target: string }>,
  nodes?: Array<{id: string; position: {x: number; y: number}; parentId?: string; style?: CSSProperties}>
): string {
  const lines: string[] = [];
  const timestamp = new Date().toISOString();
  const useSubscriptionScope = resourceGroups.length > 1;

  // Header
  lines.push(`// Generated by Azure Click to Build`);
  lines.push(`// ${timestamp}`);
  lines.push('');

  // Target scope
  if (useSubscriptionScope) {
    lines.push(`targetScope = 'subscription'`);
  } else {
    lines.push(`targetScope = 'resourceGroup'`);
  }
  lines.push('');

  // Parameters
  lines.push(`param location string = 'eastus'`);
  lines.push('');

  // Build dependency map (instanceId -> list of sanitized names it depends on)
  const idToName = new Map<string, string>();
  for (const res of resources) {
    idToName.set(res.instanceId, sanitizeName(res.name));
  }

  const dependsOnMap = new Map<string, string[]>();
  for (const edge of edges) {
    const depName = idToName.get(edge.target);
    if (depName) {
      const deps = dependsOnMap.get(edge.source) ?? [];
      deps.push(depName);
      dependsOnMap.set(edge.source, deps);
    }
  }

  // Generate resource groups (subscription scope)
  if (useSubscriptionScope) {
    for (const rg of resourceGroups) {
      const rgName = sanitizeName(rg.name);
      lines.push(
        `resource ${rgName} 'Microsoft.Resources/resourceGroups@${getApiVersion('Microsoft.Resources/resourceGroups')}' = {`
      );
      lines.push(`  name: '${rg.name}'`);
      lines.push(`  location: location`);
      lines.push(`}`);
      lines.push('');
    }

    // Group resources by resource group
    const rgResourceMap = new Map<string, CanvasResource[]>();
    for (const res of resources) {
      const rgId = res.resourceGroupId ?? 'default';
      const list = rgResourceMap.get(rgId) ?? [];
      list.push(res);
      rgResourceMap.set(rgId, list);
    }

    // Generate modules per resource group
    for (const rg of resourceGroups) {
      const rgResources = rgResourceMap.get(rg.id) ?? [];
      if (rgResources.length === 0) continue;

      const rgSanitized = sanitizeName(rg.name);
      const moduleName = `${rgSanitized}Resources`;

      lines.push(`module ${moduleName} '${toSnakeCase(rg.name)}_resources.bicep' = {`);
      lines.push(`  name: '${moduleName}'`);
      lines.push(`  scope: ${rgSanitized}`);
      lines.push(`  params: {`);
      lines.push(`    location: location`);
      lines.push(`  }`);
      lines.push(`}`);
      lines.push('');
    }

    // Generate module files content as comments
    lines.push('// --- Module files ---');
    lines.push('');

    for (const rg of resourceGroups) {
      const rgResources = rgResourceMap.get(rg.id) ?? [];
      if (rgResources.length === 0) continue;

      lines.push(`// --- File: ${toSnakeCase(rg.name)}_resources.bicep ---`);
      lines.push('');
      lines.push(`param location string`);
      lines.push('');

      for (const res of rgResources) {
        generateResourceBlock(res, lines, dependsOnMap);
      }
    }

    // Handle ungrouped resources
    const ungrouped = rgResourceMap.get('default') ?? [];
    if (ungrouped.length > 0) {
      lines.push('// --- Ungrouped resources ---');
      lines.push('');
      for (const res of ungrouped) {
        generateResourceBlock(res, lines, dependsOnMap);
      }
    }
  } else {
    // Single resource group scope — generate resource group if one exists
    if (resourceGroups.length === 1) {
      lines.push(`// Resource Group: ${resourceGroups[0].name}`);
      lines.push('');
    }

    // Generate all resources directly
    for (const res of resources) {
      generateResourceBlock(res, lines, dependsOnMap);
    }
  }

  if (nodes && nodes.length > 0) {
    lines.push(generateLayoutComment(resources, nodes, edges));
  }

  return lines.join('\n');
}

function generateLayoutComment(
  _resources: CanvasResource[],
  nodes: Array<{id: string; position: {x: number; y: number}; parentId?: string; style?: CSSProperties}>,
  edges: Array<{source: string; target: string}>
): string {
  const layout = {
    version: 1,
    nodes: nodes.map(n => ({
      id: n.id,
      x: Math.round(n.position.x),
      y: Math.round(n.position.y),
      parentId: n.parentId,
      width: n.style?.width,
      height: n.style?.height,
    })),
    edges: edges.map(e => ({ source: e.source, target: e.target })),
  };

  const json = JSON.stringify(layout);
  return [
    '',
    '// ┌──────────────────────────────────────────────────────┐',
    '// │ Azure Click to Build — Visual Layout (do not edit)   │',
    '// └──────────────────────────────────────────────────────┘',
    `// @azure-click-to-build-layout ${json}`,
    '',
  ].join('\n');
}

function generateResourceBlock(
  res: CanvasResource,
  lines: string[],
  dependsOnMap: Map<string, string[]>
): void {
  const resName = sanitizeName(res.name);
  const catalogEntry = allResources.find((r) => r.id === res.resourceId);
  const bicepType = catalogEntry?.bicepType ?? 'Microsoft.Resources/unknown';
  const apiVersion = getApiVersion(bicepType);
  const mergedProps = {
    ...(catalogEntry?.defaultProperties ?? {}),
    ...res.properties,
  };

  lines.push(
    `resource ${resName} '${bicepType}@${apiVersion}' = {`
  );
  lines.push(`  name: '${res.name}'`);
  lines.push(`  location: location`);

  // Properties
  if (Object.keys(mergedProps).length > 0) {
    lines.push(`  properties: {`);
    lines.push(formatBicepProperties(mergedProps, 4));
    lines.push(`  }`);
  } else {
    lines.push(`  properties: {}`);
  }

  // DependsOn
  const deps = dependsOnMap.get(res.instanceId);
  if (deps && deps.length > 0) {
    lines.push(`  dependsOn: [`);
    for (const dep of deps) {
      lines.push(`    ${dep}`);
    }
    lines.push(`  ]`);
  }

  lines.push(`}`);
  lines.push('');
}
