import { sanitizeName, toSnakeCase } from '../utils/codeFormatter';
import type { CanvasResource, ResourceGroup } from '../types';
import type { CSSProperties } from 'react';
import { allResources } from '../data/azureResources';

/**
 * Map from Bicep resource type to Terraform resource type.
 */
const bicepToTerraformType: Record<string, string> = {
  'Microsoft.Compute/virtualMachines': 'azurerm_linux_virtual_machine',
  'Microsoft.Compute/virtualMachineScaleSets': 'azurerm_linux_virtual_machine_scale_set',
  'Microsoft.Compute/disks': 'azurerm_managed_disk',
  'Microsoft.Web/sites': 'azurerm_linux_web_app',
  'Microsoft.Web/serverfarms': 'azurerm_service_plan',
  'Microsoft.App/containerApps': 'azurerm_container_app',
  'Microsoft.App/managedEnvironments': 'azurerm_container_app_environment',
  'Microsoft.ContainerService/managedClusters': 'azurerm_kubernetes_cluster',
  'Microsoft.Network/virtualNetworks': 'azurerm_virtual_network',
  'Microsoft.Network/networkSecurityGroups': 'azurerm_network_security_group',
  'Microsoft.Network/loadBalancers': 'azurerm_lb',
  'Microsoft.Network/publicIPAddresses': 'azurerm_public_ip',
  'Microsoft.Network/applicationGateways': 'azurerm_application_gateway',
  'Microsoft.Network/dnsZones': 'azurerm_dns_zone',
  'Microsoft.Network/networkInterfaces': 'azurerm_network_interface',
  'Microsoft.Network/privateEndpoints': 'azurerm_private_endpoint',
  'Microsoft.Storage/storageAccounts': 'azurerm_storage_account',
  'Microsoft.Sql/servers': 'azurerm_mssql_server',
  'Microsoft.Sql/servers/databases': 'azurerm_mssql_database',
  'Microsoft.DocumentDB/databaseAccounts': 'azurerm_cosmosdb_account',
  'Microsoft.Cache/redis': 'azurerm_redis_cache',
  'Microsoft.DBforPostgreSQL/flexibleServers': 'azurerm_postgresql_flexible_server',
  'Microsoft.KeyVault/vaults': 'azurerm_key_vault',
  'Microsoft.Insights/components': 'azurerm_application_insights',
  'Microsoft.OperationalInsights/workspaces': 'azurerm_log_analytics_workspace',
  'Microsoft.ContainerRegistry/registries': 'azurerm_container_registry',
  'Microsoft.ServiceBus/namespaces': 'azurerm_servicebus_namespace',
  'Microsoft.EventHub/namespaces': 'azurerm_eventhub_namespace',
  'Microsoft.CognitiveServices/accounts': 'azurerm_cognitive_account',
  'Microsoft.Search/searchServices': 'azurerm_search_service',
  'Microsoft.Resources/resourceGroups': 'azurerm_resource_group',
};

/**
 * Format a JS value as HCL.
 */
function formatHclValue(value: unknown, indent: number): string {
  const pad = ' '.repeat(indent);

  if (value === null || value === undefined) return '""';
  if (typeof value === 'string') return `"${value}"`;
  if (typeof value === 'boolean') return value.toString();
  if (typeof value === 'number') return value.toString();

  if (Array.isArray(value)) {
    if (value.length === 0) return '[]';
    const items = value.map((item) => {
      if (typeof item === 'object' && item !== null) {
        return `${pad}  {\n${formatHclBlock(item as Record<string, unknown>, indent + 4)}${pad}  }`;
      }
      return `${pad}  ${formatHclValue(item, indent + 2)}`;
    });
    return `[\n${items.join(',\n')}\n${pad}]`;
  }

  if (typeof value === 'object') {
    return `{\n${formatHclBlock(value as Record<string, unknown>, indent + 2)}${pad}}`;
  }

  return `"${String(value)}"`;
}

function formatHclBlock(
  obj: Record<string, unknown>,
  indent: number
): string {
  const pad = ' '.repeat(indent);
  const lines: string[] = [];

  for (const [key, value] of Object.entries(obj)) {
    if (value === null || value === undefined) continue;
    const hclKey = toSnakeCase(key);

    if (
      typeof value === 'object' &&
      !Array.isArray(value) &&
      value !== null
    ) {
      lines.push(`${pad}${hclKey} {`);
      lines.push(formatHclBlock(value as Record<string, unknown>, indent + 2));
      lines.push(`${pad}}`);
      lines.push('');
    } else {
      lines.push(`${pad}${hclKey} = ${formatHclValue(value, indent)}`);
    }
  }

  return lines.join('\n') + (lines.length > 0 ? '\n' : '');
}

function getTerraformType(bicepType: string): string {
  return bicepToTerraformType[bicepType] ?? `azurerm_${toSnakeCase(bicepType.split('/').pop() ?? 'resource')}`;
}

export function generateTerraform(
  resources: CanvasResource[],
  resourceGroups: ResourceGroup[],
  edges: Array<{ source: string; target: string }>,
  nodes?: Array<{id: string; position: {x: number; y: number}; parentId?: string; style?: CSSProperties}>
): string {
  const lines: string[] = [];
  const timestamp = new Date().toISOString();

  // Header
  lines.push(`# Generated by Azure Click to Build`);
  lines.push(`# ${timestamp}`);
  lines.push('');

  // Terraform block
  lines.push(`terraform {`);
  lines.push(`  required_providers {`);
  lines.push(`    azurerm = {`);
  lines.push(`      source  = "hashicorp/azurerm"`);
  lines.push(`      version = "~> 4.0"`);
  lines.push(`    }`);
  lines.push(`  }`);
  lines.push(`}`);
  lines.push('');

  // Provider
  lines.push(`provider "azurerm" {`);
  lines.push(`  features {}`);
  lines.push(`}`);
  lines.push('');

  // Variables
  lines.push(`variable "location" {`);
  lines.push(`  type    = string`);
  lines.push(`  default = "eastus"`);
  lines.push(`}`);
  lines.push('');

  // Build ID-to-terraform-name map and dependency map
  const idToTfName = new Map<string, string>();
  const idToTfType = new Map<string, string>();

  for (const res of resources) {
    const tfName = toSnakeCase(sanitizeName(res.name));
    const def = allResources.find((r) => r.id === res.resourceId);
    const tfType = getTerraformType(def?.bicepType ?? '');
    idToTfName.set(res.instanceId, tfName);
    idToTfType.set(res.instanceId, tfType);
  }

  const dependsOnMap = new Map<string, string[]>();
  for (const edge of edges) {
    const depType = idToTfType.get(edge.target);
    const depName = idToTfName.get(edge.target);
    if (depType && depName) {
      const deps = dependsOnMap.get(edge.source) ?? [];
      deps.push(`${depType}.${depName}`);
      dependsOnMap.set(edge.source, deps);
    }
  }

  // Resource group name map for references
  const rgNameMap = new Map<string, string>();
  for (const rg of resourceGroups) {
    rgNameMap.set(rg.id, toSnakeCase(sanitizeName(rg.name)));
  }

  // Resource groups
  for (const rg of resourceGroups) {
    const tfName = rgNameMap.get(rg.id)!;
    lines.push(`resource "azurerm_resource_group" "${tfName}" {`);
    lines.push(`  name     = "${rg.name}"`);
    lines.push(`  location = var.location`);
    lines.push(`}`);
    lines.push('');
  }

  // Resources
  for (const res of resources) {
    const tfType = idToTfType.get(res.instanceId)!;
    const tfName = idToTfName.get(res.instanceId)!;
    const catalogEntry = allResources.find((r) => r.id === res.resourceId);
    const mergedProps = {
      ...(catalogEntry?.defaultProperties ?? {}),
      ...res.properties,
    };

    // Determine resource group reference
    const rgTfName = res.resourceGroupId
      ? rgNameMap.get(res.resourceGroupId)
      : resourceGroups.length > 0
        ? rgNameMap.get(resourceGroups[0].id)
        : undefined;

    lines.push(`resource "${tfType}" "${tfName}" {`);
    lines.push(`  name                = "${res.name}"`);

    if (rgTfName) {
      lines.push(
        `  resource_group_name = azurerm_resource_group.${rgTfName}.name`
      );
      lines.push(
        `  location            = azurerm_resource_group.${rgTfName}.location`
      );
    } else {
      lines.push(`  location            = var.location`);
    }

    // Properties as HCL attributes
    if (Object.keys(mergedProps).length > 0) {
      lines.push('');
      lines.push(formatHclBlock(mergedProps, 2).trimEnd());
    }

    // depends_on
    const deps = dependsOnMap.get(res.instanceId);
    if (deps && deps.length > 0) {
      lines.push('');
      lines.push(`  depends_on = [`);
      for (const dep of deps) {
        lines.push(`    ${dep},`);
      }
      lines.push(`  ]`);
    }

    lines.push(`}`);
    lines.push('');
  }

  if (nodes && nodes.length > 0) {
    lines.push(generateTerraformLayoutComment(nodes, edges));
  }

  return lines.join('\n');
}

function generateTerraformLayoutComment(
  nodes: Array<{id: string; position: {x: number; y: number}; parentId?: string; style?: CSSProperties}>,
  edges: Array<{source: string; target: string}>
): string {
  const layout = {
    version: 1,
    nodes: nodes.map(n => ({
      id: n.id,
      x: Math.round(n.position.x),
      y: Math.round(n.position.y),
      parentId: n.parentId,
      width: n.style?.width,
      height: n.style?.height,
    })),
    edges: edges.map(e => ({ source: e.source, target: e.target })),
  };

  const json = JSON.stringify(layout);
  return [
    '',
    '# ┌──────────────────────────────────────────────────────┐',
    '# │ Azure Click to Build — Visual Layout (do not edit)   │',
    '# └──────────────────────────────────────────────────────┘',
    `# @azure-click-to-build-layout ${json}`,
    '',
  ].join('\n');
}
